"""
Markdown Formatter
Formats research results as structured Markdown documents.
"""

from __future__ import annotations

import re
from datetime import datetime
from pathlib import Path
from typing import Optional


class MarkdownFormatter:
    """Formats research results as Markdown with metadata."""
    
    def __init__(self, output_dir: Path = Path("outputs/research")):
        """
        Initialize formatter.
        
        Args:
            output_dir: Directory for output files
        """
        self.output_dir = output_dir
        self.output_dir.mkdir(parents=True, exist_ok=True)
    
    @staticmethod
    def sanitize_filename(text: str, max_length: int = 50) -> str:
        """
        Create safe filename from query text.
        
        Args:
            text: Original text
            max_length: Maximum filename length
            
        Returns:
            Sanitized filename
        """
        # Remove special characters
        safe = re.sub(r'[^\w\s-]', '', text.lower())
        # Replace spaces with underscores
        safe = re.sub(r'[-\s]+', '_', safe)
        # Truncate
        return safe[:max_length].strip('_')
    
    def format_research_report(
        self,
        query: str,
        content: str,
        metadata: Optional[dict] = None
    ) -> str:
        """
        Format research results as Markdown.
        
        Args:
            query: Original research query
            content: Research findings
            metadata: Optional metadata dict
            
        Returns:
            Formatted Markdown string
        """
        timestamp = datetime.now()
        
        # Build YAML frontmatter
        frontmatter = [
            "---",
            f"title: \"{query}\"",
            f"date: {timestamp.strftime('%Y-%m-%d')}",
            f"time: {timestamp.strftime('%H:%M:%S')}",
            "type: research",
        ]
        
        if metadata:
            for key, value in metadata.items():
                frontmatter.append(f"{key}: {value}")
        
        frontmatter.append("---\n")
        
        # Build document
        md_content = "\n".join(frontmatter)
        md_content += f"# {query}\n\n"
        md_content += f"*Research conducted: {timestamp.strftime('%Y-%m-%d %H:%M:%S')}*\n\n"
        md_content += "---\n\n"
        md_content += content
        md_content += "\n\n---\n\n"
        md_content += f"*Generated by DeepAgent Research System*\n"
        
        return md_content
    
    def save_research_report(
        self,
        query: str,
        content: str,
        metadata: Optional[dict] = None,
        filename: Optional[str] = None
    ) -> Path:
        """
        Save research report as Markdown file.
        
        Args:
            query: Research query
            content: Research findings
            metadata: Optional metadata
            filename: Optional custom filename
            
        Returns:
            Path to saved file
        """
        if filename is None:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            safe_query = self.sanitize_filename(query)
            filename = f"{timestamp}_{safe_query}.md"
        
        md_content = self.format_research_report(query, content, metadata)
        
        filepath = self.output_dir / filename
        filepath.write_text(md_content, encoding="utf-8")
        
        return filepath
